import { ColumnConfig } from "@/types/types";
import { formatDate } from "@/utils/dateFormatter";

export const fields: ColumnConfig[] = [
  {
    title: "User Account",
    key: "user.email",
    inputField: "select",
    selectKey: "user_id",
    inputOptions: [],
    nullable: false,
    required: true,
    readOnlyOnEdit: true,
  },
  {
    title: "Employee No.",
    key: "employee_no",
    inputField: "text",
    nullable: false,
    required: true,
    readOnly: true,
    displayAs: "chip",
    chipColor: "primary",
  },
  {
    title: "Hire Date",
    key: "hire_date",
    inputField: "date",
    nullable: true,
    required: false,
    formatter: formatDate,
  },
  {
    title: "Employment Status",
    key: "employment_status.name",
    inputField: "select",
    selectKey: "employment_status_id",
    inputOptions: [],
    nullable: true,
    required: false,
  },
  {
    title: "Department",
    key: "department.name",
    inputField: "select",
    selectKey: "department_id",
    inputOptions: [],
    nullable: true,
    required: false,
  },
  {
    title: "Position",
    key: "position.name",
    inputField: "select",
    selectKey: "position_id",
    inputOptions: [],
    nullable: true,
    required: false,
  },
  {
    title: "Job Grade",
    key: "job_grade.name",
    inputField: "select",
    selectKey: "job_grade_id",
    inputOptions: [],
    nullable: true,
    required: false,
  },
  {
    title: "Basic Monthly Salary",
    key: "basic_monthly_salary",
    inputField: "text",
    nullable: true,
    required: false,
    visibleInTable: false,
  },
  {
    title: "Pay Schedule",
    key: "pay_schedule",
    inputField: "select",
    selectKey: "pay_schedule",
    inputOptions: [
      { label: "Semi-monthly", value: "semi_monthly" },
      { label: "Monthly", value: "monthly" },
    ],
    nullable: false,
    required: true,
    visibleInTable: false,
  },
  {
    title: "Action",
    key: "action",
    inputField: "none",
    sortable: false,
    align: "center",
  },
];
